import mongoose from 'mongoose';

export default [
  {
    _id: new mongoose.Types.ObjectId('633db2570b76198b1fb9e911'),
    name: 'Semillas',
    description: 'This is a description',
    price: 2000,
    image: {
      key: 'develop/products-images/Agricultex.jpeg',
      url: 'https://qira-local.s3.amazonaws.com/develop/products-images/Agricultex.jpeg',
      _id: new mongoose.Types.ObjectId('6363bd5b1b4346383870da21'),
    },
    technicalFile: {
      key: 'randomKey',
      url: 'randomKey.jpg',
      _id: new mongoose.Types.ObjectId('633db31c0b76198b1fb9e91f'),
    },
    brand: 'Qira',
    category: {
      _id: new mongoose.Types.ObjectId('63617504bc1a382119d49e4b'),
      name: 'Herbicidas',
      image: {
        key: 'develop/categories-images/Herbicida.png',
        url: 'https://qira-local.s3.amazonaws.com/develop/categories-images/Herbicida.png',
        _id: new mongoose.Types.ObjectId('63617504bc1a382119d49e4c'),
      },
      url: 'herbicidas',
      isActive: true,
      logicDelete: false,
    },
    currency: 'DOLLAR',
    stock: 50,
    isNew: true,
  },
  {
    _id: new mongoose.Types.ObjectId('633db2bd0b76198b1fb9e919'),
    name: 'Silos bolsa',
    description: 'This is a description',
    price: 6000,
    image: {
      key: 'randomKey',
      url: 'randomKey.jpg',
      _id: new mongoose.Types.ObjectId('633db2bd0b76198b1fb9e91a'),
    },
    technicalFile: {
      key: 'randomKey',
      url: 'randomKey.jpg',
      _id: new mongoose.Types.ObjectId('633db2bd0b76198b1fb9e91b'),
    },
    brand: 'Qira',
    category: {
      _id: new mongoose.Types.ObjectId('63617567bc1a382119d49e5f'),
      name: 'Fertilizantes',
      image: {
        key: 'develop/categories-images/fertilizantes.png',
        url: 'https://qira-local.s3.amazonaws.com/develop/categories-images/fertilizantes.png',
        _id: new mongoose.Types.ObjectId('63617567bc1a382119d49e60'),
      },
      url: 'fertilizantes',
      isActive: true,
      logicDelete: false,
    },
    currency: 'PESO',
    stock: 100,
    isNew: true,
  },
  {
    _id: new mongoose.Types.ObjectId('635985d6c69ae7cc9690cd10'),
    name: 'Producto de prueba',
    description: 'This is a description',
    price: 6000,
    image: {
      key: 'randomKey',
      url: 'randomKey.jpg',
      _id: new mongoose.Types.ObjectId('635985d6c69ae7cc9690cd11'),
    },
    technicalFile: {
      key: 'randomKey',
      url: 'randomKey.jpg',
      _id: new mongoose.Types.ObjectId('635985d6c69ae7cc9690cd12'),
    },
    brand: 'Qira',
    category: {
      _id: new mongoose.Types.ObjectId('63617567bc1a382119d49e5f'),
      name: 'Fertilizantes',
      image: {
        key: 'develop/categories-images/fertilizantes.png',
        url: 'https://qira-local.s3.amazonaws.com/develop/categories-images/fertilizantes.png',
        _id: new mongoose.Types.ObjectId('63617567bc1a382119d49e60'),
      },
      url: 'fertilizantes',
      isActive: true,
      logicDelete: false,
    },
    currency: 'PESO',
    stock: 100,
    isNew: true,
  },
  {
    _id: new mongoose.Types.ObjectId('635fcea269c6117027039343'),
    name: 'Fertilizante x23',
    description: 'Descripcion',
    price: 123,
    image: {
      key: 'develop/products-images/producto.jpeg',
      url: 'https://qira-local.s3.amazonaws.com/develop/products-images/producto.jpeg',
      _id: new mongoose.Types.ObjectId('63617f280717c16a967e8aef'),
    },
    technicalFile: {
      key: 'develop/products-technical-file/PDF File example.pdf',
      url: 'https://qira-local.s3.amazonaws.com/develop/products-technical-file/PDF%20File%20example.pdf',
      _id: new mongoose.Types.ObjectId('63617f280717c16a967e8af0'),
    },
    brand: 'Marca',
    category: {
      _id: new mongoose.Types.ObjectId('63617567bc1a382119d49e5f'),
      name: 'Fertilizantes',
      image: {
        key: 'develop/categories-images/fertilizantes.png',
        url: 'https://qira-local.s3.amazonaws.com/develop/categories-images/fertilizantes.png',
        _id: new mongoose.Types.ObjectId('63617567bc1a382119d49e60'),
      },
      url: 'fertilizantes',
      isActive: true,
      logicDelete: false,
    },
    currency: 'PESO',
    stock: 123,
    isNew: true,
  },
  {
    _id: new mongoose.Types.ObjectId('63603e228384f9bb36ec76b7'),
    name: 'BugKiller',
    description: 'Mata bugs',
    price: 2500,
    image: {
      key: 'develop/products-images/producto.jpeg',
      url: 'https://qira-local.s3.amazonaws.com/develop/products-images/producto.jpeg',
      _id: new mongoose.Types.ObjectId('63617ca1a16692457d887426'),
    },
    technicalFile: {
      key: 'develop/products-technical-file/Certificado de Exclusion Retencion Percepcion Iva 09.2022.pdf',
      url: 'https://qira-local.s3.amazonaws.com/develop/products-technical-file/Certificado%20de%20Exclusion%20Retencion%20Percepcion%20Iva%2009.2022.pdf',
      _id: new mongoose.Types.ObjectId('63617ca1a16692457d887427'),
    },
    brand: 'Qira',
    category: {
      _id: new mongoose.Types.ObjectId('6361753fbc1a382119d49e55'),
      name: 'Inoculantes',
      image: {
        key: 'develop/categories-images/inoculantes.png',
        url: 'https://qira-local.s3.amazonaws.com/develop/categories-images/inoculantes.png',
        _id: '6361753fbc1a382119d49e56',
      },
      url: 'inoculantes',
      isActive: false,
      logicDelete: false,
    },
    currency: 'DOLLAR',
    stock: 13,
    isNew: true,
  },
  {
    _id: new mongoose.Types.ObjectId('63618af0e4f279774c950a77'),
    name: 'Fertimax',
    description: 'Fertilizante especial',
    price: 430,
    image: {
      key: 'develop/products-images/WhatsApp Image 2022-11-01 at 18.07.35.jpeg',
      url: 'https://qira-local.s3.amazonaws.com/develop/products-images/WhatsApp%20Image%202022-11-01%20at%2018.07.35.jpeg',
      _id: new mongoose.Types.ObjectId('63618af0e4f279774c950a78'),
    },
    technicalFile: {
      key: 'develop/products-technical-file/PDF File example.pdf',
      url: 'https://qira-local.s3.amazonaws.com/develop/products-technical-file/PDF%20File%20example.pdf',
      _id: new mongoose.Types.ObjectId('63618af0e4f279774c950a79'),
    },
    brand: 'Qira',
    category: {
      _id: new mongoose.Types.ObjectId('63617554bc1a382119d49e5a'),
      name: 'Semillas',
      image: {
        key: 'develop/categories-images/semillas.png',
        url: 'https://qira-local.s3.amazonaws.com/develop/categories-images/semillas.png',
        _id: new mongoose.Types.ObjectId('63617554bc1a382119d49e5b'),
      },
      url: 'semillas',
      isActive: true,
      logicDelete: false,
    },
    currency: 'PESO',
    stock: 100,
    isNew: true,
  },
  {
    _id: new mongoose.Types.ObjectId('63618b39e4f279774c950a7d'),
    name: 'Sulfoxaflor',
    description: 'Sulfato premium',
    price: 1500,
    image: {
      key: 'develop/products-images/Liquidex.png',
      url: 'https://qira-local.s3.amazonaws.com/develop/products-images/Liquidex.png',
      _id: new mongoose.Types.ObjectId('63618b39e4f279774c950a7e'),
    },
    technicalFile: {
      key: 'develop/products-technical-file/PDF File example.pdf',
      url: 'https://qira-local.s3.amazonaws.com/develop/products-technical-file/PDF%20File%20example.pdf',
      _id: new mongoose.Types.ObjectId('63618b39e4f279774c950a7f'),
    },
    brand: 'Sulfomax',
    category: {
      _id: new mongoose.Types.ObjectId('63617567bc1a382119d49e5f'),
      name: 'Fertilizantes',
      image: {
        key: 'develop/categories-images/fertilizantes.png',
        url: 'https://qira-local.s3.amazonaws.com/develop/categories-images/fertilizantes.png',
        _id: new mongoose.Types.ObjectId('63617567bc1a382119d49e60'),
      },
      url: 'fertilizantes',
      isActive: true,
      logicDelete: false,
    },
    currency: 'PESO',
    stock: 100,
    isNew: true,
  },
  {
    _id: new mongoose.Types.ObjectId('63618ba5e4f279774c950a83'),
    name: 'Coadload',
    description: 'Ayudante de coad',
    price: 2000,
    image: {
      key: 'develop/products-images/agrinova-gallery-curacron.jpg',
      url: 'https://qira-local.s3.amazonaws.com/develop/products-images/agrinova-gallery-curacron.jpg',
      _id: new mongoose.Types.ObjectId('63618ba5e4f279774c950a84'),
    },
    technicalFile: {
      key: 'develop/products-technical-file/Certificado de Exclusion Retencion Percepcion Iva 09.2022.pdf',
      url: 'https://qira-local.s3.amazonaws.com/develop/products-technical-file/Certificado%20de%20Exclusion%20Retencion%20Percepcion%20Iva%2009.2022.pdf',
      _id: new mongoose.Types.ObjectId('63618ba5e4f279774c950a85'),
    },
    brand: 'Qiron',
    category: {
      _id: new mongoose.Types.ObjectId('6361757fbc1a382119d49e64'),
      name: 'Coadyudantes',
      image: {
        key: 'develop/categories-images/coadyudantes.png',
        url: 'https://qira-local.s3.amazonaws.com/develop/categories-images/coadyudantes.png',
        _id: new mongoose.Types.ObjectId('6361757fbc1a382119d49e65'),
      },
      url: 'coadyudantes',
      isActive: true,
      logicDelete: false,
    },
    currency: 'DOLLAR',
    stock: 123,
    isNew: true,
  },
  {
    _id: new mongoose.Types.ObjectId('63618c11e4f279774c950a89'),
    name: 'Autoflorecientes',
    description: 'Auto',
    price: 421,
    image: {
      key: 'develop/products-images/Agricultex.jpeg',
      url: 'https://qira-local.s3.amazonaws.com/develop/products-images/Agricultex.jpeg',
      _id: new mongoose.Types.ObjectId('63618c11e4f279774c950a8a'),
    },
    technicalFile: {
      key: 'develop/products-technical-file/PDF File example.pdf',
      url: 'https://qira-local.s3.amazonaws.com/develop/products-technical-file/PDF%20File%20example.pdf',
      _id: new mongoose.Types.ObjectId('63618c11e4f279774c950a8b'),
    },
    brand: 'BSF',
    category: {
      _id: new mongoose.Types.ObjectId('63617554bc1a382119d49e5a'),
      name: 'Semillas',
      image: {
        key: 'develop/categories-images/semillas.png',
        url: 'https://qira-local.s3.amazonaws.com/develop/categories-images/semillas.png',
        _id: new mongoose.Types.ObjectId('63617554bc1a382119d49e5b'),
      },
      url: 'semillas',
      isActive: true,
      logicDelete: false,
    },
    currency: 'DOLLAR',
    stock: 204,
    isNew: true,
  },
  {
    _id: new mongoose.Types.ObjectId('636280b7185525c43278e739'),
    name: 'Nombre',
    description: 'Descripcion',
    price: 123,
    image: {
      key: 'develop/products-images/Agricultex.jpeg',
      url: 'https://qira-local.s3.amazonaws.com/develop/products-images/Agricultex.jpeg',
      _id: new mongoose.Types.ObjectId('636280b7185525c43278e73a'),
    },
    technicalFile: {
      key: 'develop/products-technical-file/PDF File example.pdf',
      url: 'https://qira-local.s3.amazonaws.com/develop/products-technical-file/PDF%20File%20example.pdf',
      _id: new mongoose.Types.ObjectId('636280b7185525c43278e73b'),
    },
    brand: 'Marca',
    category: {
      _id: new mongoose.Types.ObjectId('63617529bc1a382119d49e50'),
      name: 'Silobolsas',
      image: {
        key: 'develop/categories-images/silobolsas.png',
        url: 'https://qira-local.s3.amazonaws.com/develop/categories-images/silobolsas.png',
        _id: new mongoose.Types.ObjectId('63617529bc1a382119d49e51'),
      },
      url: 'silobolsas',
      isActive: true,
      logicDelete: false,
    },
    currency: 'PESO',
    stock: 123,
    isNew: true,
  },
];
